// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowRJbVSOtYxjrfaFKOplbl8jjmrbkIHQ',
    appId: '1:1047270364798:web:5e432fb02178515ce66a2f',
    messagingSenderId: '1047270364798',
    projectId: 'u-share-55820',
    authDomain: 'u-share-55820.firebaseapp.com',
    storageBucket: 'u-share-55820.firebasestorage.app',
    measurementId: 'G-PCT0GE5RC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByphr0RS9Vfu0XWElxDfI4DoVU09gA1UY',
    appId: '1:1047270364798:android:bc769782b82fa2b6e66a2f',
    messagingSenderId: '1047270364798',
    projectId: 'u-share-55820',
    storageBucket: 'u-share-55820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqA1BaXrRDiNx5PlYDWZ8Oa-1cTsAyChw',
    appId: '1:1047270364798:ios:c959be38f720e021e66a2f',
    messagingSenderId: '1047270364798',
    projectId: 'u-share-55820',
    storageBucket: 'u-share-55820.firebasestorage.app',
    iosBundleId: 'com.example.testProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqA1BaXrRDiNx5PlYDWZ8Oa-1cTsAyChw',
    appId: '1:1047270364798:ios:c959be38f720e021e66a2f',
    messagingSenderId: '1047270364798',
    projectId: 'u-share-55820',
    storageBucket: 'u-share-55820.firebasestorage.app',
    iosBundleId: 'com.example.testProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAowRJbVSOtYxjrfaFKOplbl8jjmrbkIHQ',
    appId: '1:1047270364798:web:033cf6746f2ece8de66a2f',
    messagingSenderId: '1047270364798',
    projectId: 'u-share-55820',
    authDomain: 'u-share-55820.firebaseapp.com',
    storageBucket: 'u-share-55820.firebasestorage.app',
    measurementId: 'G-LS53JLXWYW',
  );
}
